//import "./component-basic/props-basic-3"
//import "./component-basic/props-basic-1"
// import "./component-basic/props-children"
// import "./component-intermediate/state-study-1"
// import "./component-intermediate/sol_user_profile"
// import "./component-intermediate/state-study-3"
// import "./practice/ex01"
// import "./practice/ex02"
// import "./component-intermediate/state-study-with-inner-object"
//import "./component-intermediate/state-study-1"
// import "./component-intermediate/manipulate-list.js"
// import "./component-intermediate/todo-app-demo"
// import "./component-intermediate/comment"
//import "./component-intermediate/comment_noticeboard"
//import "./use-effect-demo/use-effect-intro"
//import "./use-effect-demo/use-effect-unmount"
//import "./practice/01_JSX/ex04"
//import "./practice/02_Props/DatePrinter"
//import "./practice/02_Props/Rectangle"
//import "./practice/02_Props/Weather"
//import "./practice/02_Props/Repeater"
//import "./practice/02_Props/ColorList"
//import "./practice/02_Props/Rating"
//import "./practice/02_Props/Alerter"
//import "./use-ref-demo/ref-demo"
//import "./use-ref-demo/reservation-form"
//import "./use-ref-demo/use-ref-practice-form"
import "./use-ref-demo/use-ref-practice-click-game"