// import "./component-basic/props-children"
// import "./component-intermediate/state-study-1"
// import "./component-intermediate/sol_user_profile"
// import "./component-intermediate/state-study-3"
// import "./practice/ex01"
// import "./practice/ex02"
// import "./component-intermediate/state-study-with-inner-object"
//import "./component-intermediate/state-study-1"
import "./component-intermediate/manipulate-list.js"